### ISSUE TITLE
Cannot npm install on system without jspm

### ISSUE THREAD

**Issue by tuxracer** [tkuminecz/decorator-decorator#1]
> npm ERR! Darwin 15.5.0
> npm ERR! argv "/usr/local/Cellar/node4-lts/4.4.4/bin/node" "/usr/local/bin/npm" "run" "jspm:install"
> npm ERR! node v4.4.4
> npm ERR! npm  v2.15.1
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! decorator-decorator@0.1.11 jspm:install: `jspm install`
> npm ERR! spawn ENOENT
> npm ERR! 
> npm ERR! Failed at the decorator-decorator@0.1.11 jspm:install script 'jspm install'.
> npm ERR! This is most likely a problem with the decorator-decorator package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     jspm install

The documentation should mention jspm as a hard requirement or (ideally) jspm is not required to install the package at all

**Comment by tkuminecz** [comment]
Hey, thanks for the feedback! It looks like this was happening due to a postinstall step in `package.json`.  
I fixed this in version 0.1.14 and I was able to install via npm so hopefully that works for you.
